set mouse=v
set comments-=s1:/**,mb:***,ex:**/
set history=500
syn on
au BufNewFile,BufRead *.thtml set filetype=php
set tags=~/tags
set makeprg=php\ -l\ %
set errorformat=%m\ in\ %f\ on\ line\ %l
set ffs=unix,dos,mac

let mapleader = "`"
inoremap <leader><leader> <leader>

inoremap <leader>inner inner
inoremap inner inner join
inoremap <leader>left left
inoremap left left outer join
inoremap <leader>right right
inoremap right right outer join
inoremap <leader>select<cr> select<cr>
inoremap select<cr> select<cr>order by<esc>Ohaving<esc>Ogroup by<esc>Owhere<esc>Ofrom<esc>O<tab>

" Appends _cstm table join statements.
" Invoke by just appending <leader>_cstm to the table name
inoremap <leader>_cstm <esc>byeoinner join <esc>pa_cstm on <esc>pa.id = <esc>pa_cstm.id_c and 0 = <esc>pa.deleted<esc>k$a

" Requires the previous line to be like what was generated by <leader><leader>_cstm
" Example invocation:
" inner join accounts_cstm on accounts.id = accounts_cstm.id_c and 0 = accounts.deleted
" inner join croom_classrooms on 1<leader>_idb -- injects the accounts_croom_classrooms_1_c table
inoremap <leader>_idb <esc>"nyl2b"byek^4w"ayeoinner join <esc>"apa_<esc>"bpa_<esc>"npa_c<esc>h"tybea on <esc>"apa.id = <esc>"tp"apa_ida and 0 = <esc>"tpa_c.deleted<esc>j$x"bpa.id = <esc>"tp"bpa_idb and 0 = <esc>"bpa.deleted

" Similar, but with ida/idb reversed
inoremap <leader>_ida <esc>"nyl2b"ayek^4w"byeoinner join <esc>"apa_<esc>"bpa_<esc>"npa_c<esc>h"tybea on <esc>"bpa.id = <esc>"tp"bpa_idb and 0 = <esc>"tpa_c.deleted<esc>j$x"apa.id = <esc>"tp"apa_ida and 0 = <esc>"bpa.deleted

" screen
"set term=builtin_ansi
execute pathogen#infect()

filetype plugin indent on
syntax on

function SqlMappings()
endfunction
inoremap <leader><?? <??
inoremap <?? <?php ?><ESC>hhi
inoremap <??<CR> <?php<CR>?><ESC>O<TAB>
inoremap <??<END> <?php<END>?>
inoremap <leader><?php <?php
inoremap <?php <?php ?><ESC>hhi
inoremap <?php<CR> <?php<CR>?><ESC>O<TAB>
inoremap <?php<END> <?php<END>?>
inoremap <?php<END><CR> <?php<CR><END><CR>?><ESC>kk<CR>i<TAB>
inoremap <leader>?> ?>
inoremap ?> <ESC>lla
inoremap <CR>?><CR> <ESC>jo
inoremap <leader>__efl__ __efl__
inoremap __efl__ echo "\n".__FILE__.":".__LINE__."[\$:]\n";

inoremap <leader>__pfl__ __pfl__
inoremap __pfl__ echo "\n<pre style='background:#062; color:#f99'>".__FILE__.":".__LINE__."[\$:]</pre>\n";

inoremap <leader>__fl__ __fl__
inoremap __fl__ __FILE__.':'.__LINE__

cnoremap <F2> :grep --exclude='*.html~' --exclude='*.thtml~' --exclude='*.php~' --exclude='*.fla' --exclude='*.swf' --exclude-dir='.svn' --exclude-dir='audio' --exclude-dir='downloads' --exclude-dir='videoTest' --exclude-dir='dbadmin' --exclude-dir='cake' --exclude-dir='statistics' --exclude-dir='tmp' --exclude-dir='anon_ftp' --exclude-dir='certificates' --exclude-dir='docs' --recursive

cnoremap <F3> :%s/“\|”/"/g<CR>
cnoremap <F4> :%s/’/'/g<CR>
cnoremap <F4> :%s/®/<sup>\&reg;<\/sup>/g<CR>
cnoremap <F5> :%s/©/<sup>\&copy;<\/sup>/g<CR>
cnoremap <F6> /\v\c\<\/?[a-z]+((\s\|\r\|\n)([a-z\-\+]+\=('[^']*'\|"[^"]*"))?)*\/?\><CR>
cnoremap <F7> /\v^[><\|=]{7}<CR>
cnoremap <F8> /\v^(\t+)([^\t].*)?$\n\1\t\t\|^\t\t(\t*).*$\n\3([^\t].*)$\| \t\|(\S\|\* )@<=\s+$\|(\S)@<=(\s{2,}\|\t)<CR>
cnoremap <F12> :source ~/.vimrc<CR>
match Ignore /\r$/

silent ! mkdir -p ~/.vim/backup ~/.cache/.vim/swap/ ~/.cache/.vim/undo
set backupdir=~/.vim/backup//
set directory=~/.cache/.vim/swap//
set undodir=~/.cache/.vim/undo//

set ts=2 sw=2
set foldmethod=indent
set hlsearch
set smartindent
set autoindent
set modeline
cmap w!! w !sudo tee > /dev/null %
